### ISSUE TITLE
how can i add an user other than 'John Lennon'?

### ISSUE THREAD

**Issue by wilsli** [strongswan/strongMan#101]
i wanna INSERT a new user into the auth_user in db.sqlite3 database, but don't know how to encrypt the 'password' field, could you state a little bit more in docs?

**Comment by tobiasbrunner** [comment]
The password is set via [set_password()](https://docs.djangoproject.com/en/dev/topics/auth/customizing/#django.contrib.auth.models.AbstractBaseUser.set_password), which, I think, internally uses [make_password()](https://docs.djangoproject.com/en/dev/topics/auth/passwords/#module-django.contrib.auth.hashers). You may use the Django shell to call that:

    $ . env/bin/activate
    (env) $ python manage.py shell --settings=strongMan.settings.local
    >>> from django.contrib.auth.hashers import make_password
    >>> make_password("...")

Hope this helps.

**Comment by wilsli** [comment]
@tobiasbrunner Thank you!
