### ISSUE TITLE
Running StrongMan on existing StrongSwan setup

### ISSUE THREAD

**Issue by lsadehaan** [strongswan/strongMan#107]
We have an existing StrongSwan install configured through the ipsec.conf config file manually. 
I'm considering migrating to StrongMan to have a GUI interface, but I cannot have much downtime.
Is it possible to run StrongMan on the same machine at the same time and move the configuration from the config file based setup to the StrongMan managed database in a safe manner? 
Any recommendation on how to make this migration?

**Comment by tobiasbrunner** [comment]
Possibly, but strongMan requires the [vici](https://wiki.strongswan.org/projects/strongswan/wiki/Vici) plugin. Since you currently use ipsec.conf (which uses the _stroke_ plugin and starter) you might not have that loaded yet. So you'll probably have to restart the daemon anyway.
