### ISSUE TITLE
Setup strongMan on the existing configuration

### ISSUE THREAD

**Issue by perrfect** [strongswan/strongMan#110]
Hi.
I want to try strongMan on my existing server with strongswan.
How can i add my existing configs strongswan to new installation strongMan?

**Comment by tobiasbrunner** [comment]
> How can i add my existing configs strongswan to new installation strongMan?

There is no automated way to do that.

**Comment by perrfect** [comment]
Hi.
Which rules for iptables should be open?

**Comment by tobiasbrunner** [comment]
For strongMan it depends on how you deploy it (e.g. TCP/443), for IKE/IPsec you'll need to open UDP ports 500 and 4500 (and if clients are not behind a NAT, IP protocol 50/ESP)
