### ISSUE TITLE
Problem with Windows 10 clients

### ISSUE THREAD

**Issue by perrfect** [strongswan/strongMan#111]
Hi.
I use strongMan, but have some problems with connect windows 10 clients
My windows 10 client connected, but packages only transfered, but are not accepted
I disable all my firewall on win10.
Could you help me?

**Comment by perrfect** [comment]
And in log strongswan i see:

[IKE] received DELETE for ESP CHILD_SA with SPI 681de14c
Dec 20 12:44:30 test.test: 16[IKE] closing CHILD_SA test.test{86} with SPIs 17ed9ae0_i (3332 bytes) 681de14c_o (0 bytes) and TS 0.0.0.0/0 === 10.15.1.11/32
Dec 20 12:44:30 test.test: 16[IKE] sending DELETE for ESP CHILD_SA with SPI 17ed9ae0
Dec 20 12:44:30 test.test: 16[IKE] CHILD_SA closed

**Comment by tobiasbrunner** [comment]
Wrong issue tracker. See [here](https://wiki.strongswan.org/projects/strongswan/wiki/HelpRequests) for help on general strongSwan issues.
