### ISSUE TITLE
Auto renew ssl for strongMan

### ISSUE THREAD

**Issue by perrfect** [strongswan/strongMan#112]
Hi.
How can auto renew ssl for strongMan?
In which directory are the certificates?
And when i add new ssl through command line should i restart strongMan?

**Comment by perrfect** [comment]
Hi.
Do you have some idea?

**Comment by tobiasbrunner** [comment]
Certificates loaded via strongMan are not stored in a database, not on disk. I guess you could update the database and trigger the `configloader.py` script. But it's probably easier to just configure such certificates directly in the daemon (see the [user documentation](https://wiki.strongswan.org/projects/strongswan/wiki/UserDocumentation) on the wiki) and reload them once they change.

**Comment by perrfect** [comment]
Ok, thank you.
And I have another question.
Can I use my url http://localhost:1515 for https?
And where can I change this setting?

**Comment by perrfect** [comment]
Hi.
How can I delete my server configuration when i change the certificate and i get the error:


Request Method: | GET
-- | --
http://vpn-test:1515/server_connections/1/
1.9.6
AssertionError
/root/strongMan/strongMan/apps/server_connections/forms/SubForms.py in fill, line 396

**Comment by tobiasbrunner** [comment]
Check your web server's documentation on how you get HTTPS working.
