### ISSUE TITLE
How can delete server_connections?

### ISSUE THREAD

**Issue by perrfect** [strongswan/strongMan#113]
Hello.
I want to delete "server_connections", because I changed my certificate and when i want to enter my "server_connections" i get error:

`http://vpn-test:1515/server_connections/1/
1.9.6
AssertionError
/root/strongMan/strongMan/apps/server_connections/forms/SubForms.py in fill, line 396
/root/strongMan/env/bin/python3
3.6.8
['/root/strongMan',  '/root/strongMan/env/bin',  '/root/strongMan/env/lib64/python36.zip',  '/root/strongMan/env/lib64/python3.6',  '/root/strongMan/env/lib64/python3.6/lib-dynload',  '/usr/lib64/python3.6',  '/usr/lib/python3.6',  '/root/strongMan/env/lib/python3.6/site-packages']`

So, I want to delete this configuration and create new, but don't want to delete my users from "EAP Secrets".
How can I do it?

**Comment by tobiasbrunner** [comment]
What do you mean with _"delete "server_connections""_? What exactly did you do?

**Comment by perrfect** [comment]
I mean that I want to delete my existing configuration, because when i want to see the configuration or change i get error.

`Traceback (most recent call last):
File "/root/strongMan/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 149, in get_response
response = self.process_exception_by_middleware(e, request)
File "/root/strongMan/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 147, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/root/strongMan/env/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
return view_func(request, *args, **kwargs)
File "/root/strongMan/strongMan/apps/server_connections/views/__init__.py", line 35, in update
return handler.handle()
File "/root/strongMan/strongMan/apps/server_connections/views/UpdateHandler.py", line 52, in handle
return self._render()
File "/root/strongMan/strongMan/apps/server_connections/views/UpdateHandler.py", line 28, in _render
form.fill(self.connection)
File "/root/strongMan/strongMan/apps/server_connections/forms/ConnectionForms.py", line 103, in fill
base.fill(self, connection)
File "/root/strongMan/strongMan/apps/server_connections/forms/SubForms.py", line 396, in fill
assert False
AssertionError
`
I deleted my existing certificate from server, but i didn't delete the certificate from my configuration.

**Comment by tobiasbrunner** [comment]
> I deleted my existing certificate from server, but i didn't delete the certificate from my configuration.

What does that mean? Did you modify the database manually?

**Comment by perrfect** [comment]
No.
I deleted my certificate from tab "Certificates".
And after that i restarted strongMan as service.
But i didn't delete my certificate from "Server Connection" tab and get error.

**Comment by perrfect** [comment]
Do you have any ideas how can i restore my configuration?

**Comment by tobiasbrunner** [comment]
> Do you have any ideas how can i restore my configuration?

Presumably, the database is in an inconsistent state. So I guess you'd have to manually add a certificate (or rather identity) entry with the same ID as the previous one (the one still referenced by the connection). Otherwise, deleting the connection entry might be the only option.

I saw that there is a check that should prevent deleting certificates if they are in use by a connection. I wonder why that didn't work here.

**Comment by perrfect** [comment]
> > Do you have any ideas how can i restore my configuration?
> 
> Presumably, the database is in an inconsistent state. So I guess you'd have to manually add a certificate (or rather identity) entry with the same ID as the previous one (the one still referenced by the connection). Otherwise, deleting the connection entry might be the only option.
> 
> I saw that there is a check that should prevent deleting certificates if they are in use by a connection. I wonder why that didn't work here.

Hi.
Thank you for reply
I've been testing new configuration and noticed that when I create new "Connection" and upload new certificate (on tab "Server Connections",  field "Server certificate") and after that delete this certificate from tab "Server certificate", get error which i described above.

**Comment by tobiasbrunner** [comment]
I finally had some time to look into this. It turns out that the check that should prevent deletion of in-use certificates I mentioned above was not correct. The code was copy-pasted from the client connection app without necessary modifications to take into account properties of server connections. I pushed a fix to master.
