### ISSUE TITLE
Error running setup.py

### ISSUE THREAD

**Issue by limace255** [strongswan/strongMan#115]
Hi there,
I want to try this UI for strongswan.
When I follow the instructions, I get following errors : 

> ./setup.py install
Start strongMan installation
	- Virtualenv
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--app-data APP_DATA] [--clear-app-data] [--discovery {builtin}] [-p py] [--creator {builtin,cpython3-posix,venv}] [--seeder {app-data,pip}] [--no-seed]
                  [--activators comma_sep_list] [--clear] [--system-site-packages] [--symlinks | --copies] [--download | --no-download] [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip]
                  [--no-setuptools] [--no-wheel] [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: unrecognized arguments: --no-site-packages
Command '['virtualenv', '-p', 'python3', '--no-site-packages', '/opt/stringman/strongMan/env']' returned non-zero exit status 2

Is this due to my virtualenv package version ?
Here is my configuration : 
python3
virtualenv (20.0.7)

Thanks in advance

**Comment by limace255** [comment]
Replacing "no-site-packages" by "system-site-packages" obviously helped, but I'm not sure that it's what you want, by the way

**Comment by limace255** [comment]
Ok, sorry for the noise, and not sure if this is the appropriate place for that : 
I think that during setup.py, packages installation of requirements.txt does not happen inside the virtualenv.
I faced some errores after changing " --no-site-packages " by " system-site-packages", but then, at least, te whole process was good.
Then, when adding the service, it failed, saying "no gunicorn" in the "env" path.
I made following : 
- virtualenv env
- source env/bin/activate
- pip install -r requirements.txt
Then, everything was Ok, even add-service.

**Comment by tobiasbrunner** [comment]
Thanks for the report. As far as I can tell, `--no-site-packages` has been deprecated for over 8 years ([v1.7](https://virtualenv.pypa.io/en/legacy/changes.html#v1-7-2011-11-30)) and its behavior has been the default since then. You probably shouldn't replace it with `--system-site-packages` but just remove it instead. Pushed a fix to the _115-virtualenv-fix_ branch.
