### ISSUE TITLE
I get this warning

### ISSUE THREAD

**Issue by ebadola** [strongswan/strongMan#120]
/var/run/charon.vici doesn't exist!
I don't know what to do?

**Comment by tobiasbrunner** [comment]
That socket is created by strongSwan's _vici_ plugin. An IKE daemon (_charon_ or _charon-systemd_) with that plugin loaded must be running in the background so strongMan can interact with the daemon.

**Comment by yolowex** [comment]
Hi, even in the documentation I can't find the instructions of how to install and enable the vici plugin.
https://docs.strongswan.org/docs/latest/plugins/vici.html

please tell me how to enable this daemon

**Comment by tobiasbrunner** [comment]
Depends on how you installed strongSwan (see [the docs](https://docs.strongswan.org/docs/latest/install/install.html)).
