### ISSUE TITLE
Virtualenv is required and not installed.

### ISSUE THREAD

**Issue by githubuser00** [strongswan/strongMan#125]
Virtualenv is required and not installed
`
ubuntu@swan:~$ pip install virtualenv
Requirement already satisfied: virtualenv in ./.local/lib/python3.9/site-packages (20.4.6)
Requirement already satisfied: six<2,>=1.9.0 in /usr/lib/python3/dist-packages (from virtualenv) (1.15.0)
Requirement already satisfied: filelock<4,>=3.0.0 in ./.local/lib/python3.9/site-packages (from virtualenv) (3.0.12)
Requirement already satisfied: appdirs<2,>=1.4.3 in ./.local/lib/python3.9/site-packages (from virtualenv) (1.4.4)
Requirement already satisfied: distlib<1,>=0.3.1 in ./.local/lib/python3.9/site-packages (from virtualenv) (0.3.1)
ubuntu@swan:~$ cd strongMan-master/
ubuntu@swan:~/strongMan-master$ sudo ./setup.py install
[sudo] password for ubuntu:
[Errno 2] No such file or directory
Virtualenv is required and not installed.
ubuntu@swan:~/strongMan-master$
`

**Comment by tobiasbrunner** [comment]
The root user probably does not have that executable in its PATH. Looks like `pip` installed stuff in your home directory (see the `./.local` path), did you try running that as root too?
