### ISSUE TITLE
No proposal chosen

### ISSUE THREAD

**Issue by dedisoft** [strongswan/strongMan#131]
Hi,

I'm trying your solution and it seems to be very great.

We have an error when trying connection :

received NO_PROPOSAL_CHOSEN notify error

It seems that no encryption is proposed.

Have I missed something on the interface ?

How can I set a default proposal to Strongswan ?

Many thanks !

Regards,

**Comment by tobiasbrunner** [comment]
See my comment here: https://github.com/strongswan/strongMan/issues/130#issuecomment-937869979

**Comment by dedisoft** [comment]
Thanks for your quick reply !
