### ISSUE TITLE
EAP Password

### ISSUE THREAD

**Issue by TigerMax** [strongswan/strongMan#132]
Hello!
EAP Secret password add salt after strongswan-service reboot.
Example:
Adding new secret in StrongMan:
Username: testuser
Password: testpassword
Save;
When i press Show password it adds salt(example: d3testuser2'), but password is correct. (testpassword)
After rebooting strongswan service new password is d3testuser2', with salt.

**Comment by tobiasbrunner** [comment]
I think this has been fixed with 179becd7eb2dc461725ec358e6e00d9cfc7d837b.
