### ISSUE TITLE
/var/run/charon.vici doesn't exist!

### ISSUE THREAD

**Issue by Earthquake939** [strongswan/strongMan#134]
Hi friends!

We've succesfully install this project on centOS (rhel7), the python django gui can communicate with strongswan daemon through vici plugin and we have no errors on the web administration. (Our strongswan installation uses ipsec.conf and not swanctl.conf)

root#strongswan --version (installed with yum and not builded with make)

Linux strongSwan U5.7.2/K3.10.0-1160.62.1.el7.x86_64
University of Applied Sciences Rapperswil, Switzerland

But when we try to install the project on centOS (rhel8), with the same installation steps and all the strongswan dependencies and pip requirements; we have an error message at django web gui that says "/var/run/charon.vici doesn't exist!" and the web administration doesn't works well and some features can't be opened. (Our strongswan installation uses ipsec.conf and not swanctl.conf)

root#strongswan --version (installed with dnf and not builded with make)
Linux strongSwan U5.9.5/K4.18.0-372.13.1.el8_6.x86_64
University of Applied Sciences Rapperswil, Switzerland

On both operating systems (rhel7 & rhel8) the ikev2 strongswan daemon works very well, but the strongman project can connect detect the vici plugins on rhel8 even if exists in the kernel.

We await for your comments please!

Best Regards.
Christian Mora
Ecuador - Quito

**Comment by tobiasbrunner** [comment]
The file is either in a different location (possible as the EPEL package changes other stuff too, like renaming the `ipsec` script to `strongswan` or having all configuration files in `/etc/strongswan`), or strongMan has no access to it (this could probably be fixed by using a specific group for the daemon).
