### ISSUE TITLE
error on startup.py

### ISSUE THREAD

**Issue by Prolasis** [strongswan/strongMan#139]
when i isntall following the guide i get nothing when going to localhost:1515. When i try to go directly to the private IP 10.0.2.0 etc i get below. I have my install on ubuntu 20 server. is there something i missed during setup. thanks

> 
> -text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Invalid HTTP_HOST header: '172.17.0.1:1515'. You may need to add '172.17.0.1' to ALLOWED_HOSTS.</pre>
> 
> Request Method: | GET
> -- | --
> http://172.17.0.1:1515/
> 3.1.13
> DisallowedHost
> Invalid HTTP_HOST header: '172.17.0.1:1515'. You may need to add '172.17.0.1' to ALLOWED_HOSTS.
> /home/strongswan/strongMan/env/lib/python3.8/site-packages/django/http/request.py, line 137, in get_host
> /home/strongswan/strongMan/env/bin/python
> 3.8.10
> ['/home/strongswan/strongMan',  '/home/strongswan/strongMan/env/bin',  '/usr/lib/python38.zip',  '/usr/lib/python3.8',  '/usr/lib/python3.8/lib-dynload',  '/home/strongswan/strongMan/env/lib/python3.8/site-packages']
> Mon, 10 Jul 2023 16:59:24 +0000
> 
> 
> </body>
> </html>

**Comment by Prolasis** [comment]
do i need to install this on a desktop not server? I tried changing the deployment file but just a white page it cant find

**Comment by TelDragon** [comment]
I successfully opened the page by adding my host IP address or accessing the URL address here.

[https://github.com/strongswan/strongMan/blob/3934ad3bf53da0d70b1ad52f44db5a9fc7742073/strongMan/settings/base.py#L5](https://github.com/strongswan/strongMan/blob/3934ad3bf53da0d70b1ad52f44db5a9fc7742073/strongMan/settings/base.py#L5)
